### ISSUE TITLE
code_off-7-1.in is invalid

### ISSUE THREAD

**Issue by keegancsmith** [prolific-idea/Code-Off#3]
Instead of having an endpoint marked `1` or `2`, it has endpoints marked `U`
Direct link https://github.com/prolific-idea/Code-Off/blob/master/code_off-7/code_off-7-1.in

cc @rishal-hurbans

**Comment by rishal-hurbans** [comment]
Thanks for spotting that! It was a careless mistake on my side. Apologies. It's been fixed.
